### ISSUE TITLE
Not all SWW files are supported

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#137]
See https://github.com/qgis/QGIS/issues/30828

**Comment by saberraz** [comment]
Here is the output, when I run `mdalinfo`

```
mdalinfo /tmp/test1.sww 
mdalinfo 0.3.2
Mesh File: /tmp/test1.sww
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140414546728128:
  #000: ../../../src/H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5Fint.c line 1400 in H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: ../../../src/H5Fint.c line 1700 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #003: ../../../src/H5Fsuper.c line 411 in H5F__super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
corrupted size vs. prev_size
Aborted (core dumped)
```

**Comment by schoeller** [comment]
@saberraz 
If understood correctly from above output, the driver loading the file is HDF5. Browsing the Anuga code, files are handled by NetCDF only (https://github.com/GeoscienceAustralia/anuga_core/blob/3e9f18a43676ba20e524b86806814892c28e561f/anuga/file/sww.py). Loading the file through NetCDF seems possible
```
> ncdump -h .\examples\test1.sww
netcdf test1 {
dimensions:
        number_of_volumes = 16 ;
        number_of_triangle_vertices = 13 ;
        number_of_vertices = 3 ;
        numbers_in_range = 2 ;
        number_of_points = 13 ;
        number_of_timesteps = UNLIMITED ; // (3 currently)
variables:
        float x(number_of_points) ;
        float y(number_of_points) ;
        int volumes(number_of_volumes, number_of_vertices) ;
        float elevation(number_of_points) ;
        float elevation_range(numbers_in_range) ;
        float friction(number_of_points) ;
        float friction_range(numbers_in_range) ;
        float elevation_c(number_of_volumes) ;
        float friction_c(number_of_volumes) ;
        float xmomentum(number_of_timesteps, number_of_points) ;
        float xmomentum_range(numbers_in_range) ;
        float ymomentum(number_of_timesteps, number_of_points) ;
        float ymomentum_range(numbers_in_range) ;
        float stage(number_of_timesteps, number_of_points) ;
        float stage_range(numbers_in_range) ;
        float xmomentum_c(number_of_timesteps, number_of_volumes) ;
        float ymomentum_c(number_of_timesteps, number_of_volumes) ;
        float stage_c(number_of_timesteps, number_of_volumes) ;
        double time(number_of_timesteps) ;

// global attributes:
                :institution = "Geoscience Australia" ;
                :description = "Output from anuga.file.sww suitable for plotting" ;
                :smoothing = "Yes" ;
                :vertices_are_stored_uniquely = "False" ;
                :order = 2 ;
                :revision_number = "9737" ;
                :anuga_version = "2.0.3" ;
                :starttime = 0 ;
                :xllcorner = 0. ;
                :yllcorner = 0. ;
                :zone = -1 ;
                :false_easting = 500000 ;
                :false_northing = 10000000 ;
                :datum = "wgs84" ;
                :projection = "UTM" ;
                :units = "m" ;
}
```
Anuga_viewer.exe is able to read the output
![image](https://user-images.githubusercontent.com/106036/62194669-d94ab280-b369-11e9-91f6-327798d65d14.png)

I am trying to grasp the loading mechanism for how a driver is chosen for loading. As far as I am able to understand the code, the mechanism is as follows:
0#A driver is defined
1#It is then being pushed to the driver manager via ```MDAL::DriverManager::DriverManager()``` and indexed there. So drivers have a sequential order
2#When opening a file a loop within ```MDAL::DriverManager::load``` checks for ```hasCapability```, which is determined in ```MDAL_DR_meshLoadCapability``` and loads through the first driver found

Please comment whether I am on the right track. My skills are limited so patience is welcome.

Best

Sebastian

**Comment by wonder-sk** [comment]
@schoeller you can ignore the HDF messages - those are coming from HDF library when it fails to open the file. You are on the right track with driver manager. The driver used for Anuga files is called DriverSWW.

I have briefly tried to load the file in QGIS and this is the backtrace:
```
#0  0x00007ffff2050e97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff2052801 in __GI_abort () at abort.c:79
#2  0x00007ffff209b897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff21c8b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff20a290a in malloc_printerr (str=str@entry=0x7ffff21c6e0e "malloc(): memory corruption") at malloc.c:5350
#4  0x00007ffff20a6994 in _int_malloc (av=av@entry=0x7ffff23fdc40 <main_arena>, bytes=bytes@entry=16000) at malloc.c:3738
#5  0x00007ffff20a92ed in __GI___libc_malloc (bytes=16000) at malloc.c:3065
#6  0x00007ffff26ae258 in operator new(unsigned long) () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7565836 in __gnu_cxx::new_allocator<double>::allocate(unsigned long, void const*) (this=0x7fffffffc2e0, __n=2000) at /usr/include/c++/7/ext/new_allocator.h:111
#8  0x00007ffff75652d3 in std::allocator_traits<std::allocator<double> >::allocate(std::allocator<double>&, unsigned long) (__a=..., __n=2000) at /usr/include/c++/7/bits/alloc_traits.h:436
#9  0x00007ffff7564aac in std::_Vector_base<double, std::allocator<double> >::_M_allocate(unsigned long) (this=0x7fffffffc2e0, __n=2000) at /usr/include/c++/7/bits/stl_vector.h:172
#10 0x00007ffff7563da9 in std::_Vector_base<double, std::allocator<double> >::_M_create_storage(unsigned long) (this=0x7fffffffc2e0, __n=2000) at /usr/include/c++/7/bits/stl_vector.h:187
#11 0x00007ffff756292d in std::_Vector_base<double, std::allocator<double> >::_Vector_base(unsigned long, std::allocator<double> const&) (this=0x7fffffffc2e0, __n=2000, __a=...)
    at /usr/include/c++/7/bits/stl_vector.h:138
#12 0x00007ffff0664d2e in std::vector<double, std::allocator<double> >::vector(unsigned long, std::allocator<double> const&) (this=0x7fffffffc2e0, __n=2000, __a=...)
    at /usr/include/c++/7/bits/stl_vector.h:284
#13 0x00007fffa55f58ce in MDAL::calculateStatistics(std::shared_ptr<MDAL::Dataset>) (dataset=std::shared_ptr<MDAL::Dataset> (use count 2, weak count 0) = {...})
    at ../external/mdal/mdal_utils.cpp:438
#14 0x00007fffa56673e1 in MDAL::DriverSWW::readScalarGroup(NetCDFFile const&, MDAL::MemoryMesh*, std::vector<double, std::allocator<double> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const (this=0x5555572b4070, ncFile=..., mesh=
    0x555556b77990, times=std::vector of length 3, capacity 3 = {...}, groupName="friction_c", arrName="friction_c") at ../external/mdal/frmts/mdal_sww.cpp:304
#15 0x00007fffa566694c in MDAL::DriverSWW::readDatasetGroups(NetCDFFile const&, MDAL::MemoryMesh*, std::vector<double, std::allocator<double> > const&) const (this=0x5555572b4070, ncFile=..., mesh=0x555556b77990, times=std::vector of length 3, capacity 3 = {...}) at ../external/mdal/frmts/mdal_sww.cpp:217
#16 0x00007fffa566844c in MDAL::DriverSWW::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MDAL_Status*) (this=0x5555572b4070, resultsFile="/home/martin/tmp/bug-sww-crash/test1.sww", status=0x7fffa58d0140 <sLastStatus>) at ../external/mdal/frmts/mdal_sww.cpp:456
#17 0x00007fffa56025ae in MDAL::DriverManager::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MDAL_Status*) const (this=0x7fffa58d0190 <MDAL::DriverManager::instance()::sInstance>, meshFile="/home/martin/tmp/bug-sww-crash/test1.sww", status=0x7fffa58d0140 <sLastStatus>) at ../external/mdal/mdal_driver_manager.cpp:54
#18 0x00007fffa55f169d in MDAL_LoadMesh(char const*) (meshFile=0x5555570885d8 "/home/martin/tmp/bug-sww-crash/test1.sww") at ../external/mdal/mdal.cpp:143
```

The problem will be probably somewhere in DriverSWW::readScalarGroup() but I haven't had time to investigate further yet.

**Comment by PeterPetrik** [comment]
fixed on master, will appear in MDAL 0.3.4 or 0.4.0

**Comment by stoiver** [comment]
@saberraz @PeterPetrik Just noticed this issue. First great job with the mdal package.. 

I did notice on the latest cond-forge version of qgis/mdal that _c versions of the sww data sets are visualised, but they don't seem to be actually matching the correct information. The _c denotes centroid based data, ie just one value for each triangle. So wondering what assumptions are being used by mdal when reading the _c data sets.

**Comment by PeterPetrik** [comment]
hi @stoiver .  There was a bug (crashing qgis/mdal) for previous versions , so we hot-fixed it to ignore all volume based SWW variables. To implement it, we need to fix https://github.com/lutraconsulting/MDAL/issues/142
